banca = {"diners" : 1000000}

jugadors = {
    "Blau" : {
        "diners" : 2000,
        "torn" : None,
        "carrers" : "(res)",
        "especial" : "(res)",
        "ID_casella" : 0,
        "és_presoner": False,
        "torns_presoner": 0
    },
    "Groc" : {
        "diners" : 2000,
        "torn" : None,
        "carrers" : "(res)",
        "especial" : "(res)",
        "ID_casella" : 0,
        "és_presoner": False,
        "torns_presoner": 0
    },
    "Taronja" : {
        "diners" : 2000,
        "torn" : None,
        "carrers" : "(res)",
        "especial" : "(res)",
        "ID_casella" : 0,
        "és_presoner": False,
        "torns_presoner": 0
    },
    "Vermell" : {
        "diners" : 2000,
        "torn" : None,
        "carrers" : "(res)",
        "especial" : "(res)",
        "ID_casella" : 0,
        "és_presoner": False,
        "torns_presoner": 0
    },
}
caselles = [
    {
        "nom": "Sortida",
        "nom curt":"Sortida",
        "tipus": "especial",
        "jugadors": [],
        "fil_col_taulell": [6,6]
    },
    {
        "nom": "Lauria",
        "nom curt": "Lauria",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 10,
        "lloguer hotel": 15,
        "comprar terreny": 50,
        "comprar casa": 200,
        "comprar hotel": 250,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [6,5]
    },
    {
        "nom": "Rosselló",
        "nom curt": "Rosell",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 10,
        "lloguer hotel": 15,
        "comprar terreny": 50,
        "comprar casa": 225,
        "comprar hotel": 255,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [6,4]
    },
    {
        "nom": "Sort",
        "nom curt": "Sort",
        "tipus": "especial",
        "jugadors": [],
        "fil_col_taulell": [6,3]
    },
    {
        "nom": "Marina",
        "nom curt": "Marina",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 15,
        "lloguer hotel": 15,
        "comprar terreny": 50,
        "comprar casa": 250,
        "comprar hotel": 260,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [6,2]
    },
    {
        "nom": "C. de cent",
        "nom curt": "Consell",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 15,
        "lloguer hotel": 20,
        "comprar terreny": 50,
        "comprar casa": 275,
        "comprar hotel": 265,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [6,1]
    },
    {
        "nom": "Presó",
        "nom curt": "Presó",
        "tipus": "especial", 
        "jugadors": [],
        "fil_col_taulell": [6,0]
    },
    {
        "nom": "Muntaner",
        "nom curt": "Muntan",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 20,
        "lloguer hotel": 20,
        "comprar terreny": 60,
        "comprar casa": 300,
        "comprar hotel": 270,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [5,0]
    },
    {
        "nom": "Aribau",
        "nom curt": "Aribau",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 20,
        "lloguer hotel": 20,
        "comprar terreny": 60,
        "comprar casa": 325,
        "comprar hotel": 275,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [4,0]
    },
    {
        "nom": "Caixa",
        "nom curt": "Caixa",
        "tipus": "especial",
        "jugadors": [],
        "fil_col_taulell": [3,0]
    },
    {
        "nom": "Sant Joan",
        "nom curt": "St.Joan",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 25,
        "lloguer hotel": 25,
        "comprar terreny": 60,
        "comprar casa": 350,
        "comprar hotel": 280,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [2,0]
    },
    {
        "nom": "Aragó",
        "nom curt": "Aragó",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 25,
        "lloguer hotel": 25,
        "comprar terreny": 60,
        "comprar casa": 375,
        "comprar hotel": 285,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [1,0]
    },
    {
        "nom": "Parking",
        "nom curt": "Parking",
        "tipus": "especial",
        "jugadors": [],
        "fil_col_taulell": [0,0]
    },
    {
        "nom": "Urquinaona",
        "nom curt": "Urqinoa",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 30,
        "lloguer hotel": 25,
        "comprar terreny": 70,
        "comprar casa": 400,
        "comprar hotel": 290,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [0,1]
    },
    {
        "nom": "Fontana",
        "nom curt": "Fontan",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 30,
        "lloguer hotel": 30,
        "comprar terreny": 70,
        "comprar casa": 425,
        "comprar hotel": 300,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [0,2]
    },
    {
        "nom":"Sort",
        "nom curt":"Sort",
        "tipus": "especial",
        "funcio": "Sort",
        "jugadors": [],
        "fil_col_taulell": [0,3]
    },
    {
        "nom": "Les Rambles",
        "nom curt": "Rambles",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 35,
        "lloguer hotel": 30,
        "comprar terreny": 70,
        "comprar casa": 450,
        "comprar hotel": 310,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [0,4]
    },
    {
        "nom": "Pl. Catalunya",
        "nom curt": "Pl.Cat",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 35,
        "lloguer hotel": 30,
        "comprar terreny": 70,
        "comprar casa": 475,
        "comprar hotel": 320,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [0,5]
    },
    {
        "nom":"Anar preso",
        "nom curt":"Anr pró",
        "tipus": "especial",
        "funcio": "AnarPreso",
        "jugadors": [],
        "fil_col_taulell": [0,6]
    },
    {
        "nom": "P. Àngel",
        "nom curt": "Angel",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 40,
        "lloguer hotel": 35,
        "comprar terreny": 80,
        "comprar casa": 500,
        "comprar hotel": 330,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [1,6]
    },
    {
        "nom": "Via Augusta",
        "nom curt": "Augusta",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 40,
        "lloguer hotel": 35,
        "comprar terreny": 80,
        "comprar casa": 525,
        "comprar hotel": 340,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [2,6]
    },
    {
        "nom":"Caixa",
        "nom curt":"Caixa",
        "tipus": "especial",
        "funcio": "Caixa",
        "jugadors": [],
        "fil_col_taulell": [3,6]
    },
    {
        "nom": "Balmes",
        "nom curt": "Balmes",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 50,
        "lloguer hotel": 40,
        "comprar terreny": 80,
        "comprar casa": 550,
        "comprar hotel": 350,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [4,6]
    },
    {
        "nom": "Pg. de Gracia",
        "nom curt": "Gracia",
        "tipus": "carrer",
        "propietari": "Banca",
        "lloguer casa": 50,
        "lloguer hotel": 50,
        "comprar terreny": 80,
        "comprar casa": 525,
        "comprar hotel": 360,
        "nombre cases": 0,
        "nombre hotels": 0,
        "jugadors": [],
        "fil_col_taulell": [5,6]
    }
]
